services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: budget_app
      POSTGRES_USER: budget
      POSTGRES_PASSWORD: budget
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget -d budget_app"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    command: sh -c "uv run alembic upgrade head && uv run uvicorn app.main:app --host 0.0.0.0 --port 80"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
