version: '3'

includes:
  dev: ./taskfiles/dev.yml
  db:  ./taskfiles/db.yml

tasks:
  help:
    desc: Show this help message
    cmds:
      - task --list

  dev:
    desc: Start development environment
    cmds:
      - task dev:dev
