version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
      - uv sync

  dev:
    desc: Start the development server
    cmds:
      - uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  test:
    desc: Run tests
    cmds:
      - uv run pytest --cov=app --cov-report=term-missing

  lint:
    desc: Run linter
    cmds:
      - uv run ruff check .

  format:
    desc: Format code
    cmds:
      - uv run ruff format .

  type-check:
    desc: Run type checker
    cmds:
      - uv run mypy .

  clean:
    desc: Remove temporary files
    cmds:
      - find . -type d -name __pycache__ -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete
      - find . -type d -name ".pytest_cache" -exec rm -rf {} +

  check:
    desc: Run all code checks
    deps: [lint, type-check]

  ci:
    desc: Full CI checks
    deps: [install, check, test]
