version: '3.9'
services:
  app:
    build: .
    volumes:
      - ..:/workspace:cached
    command: sleep infinity  # VS Code がアタッチ後 devcontainer.json の post* で起動
    environment:
      DB_DSN: postgresql://budget:budget@db:5432/budget_app
      APP_ENV: dev
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: budget
      POSTGRES_PASSWORD: budget
      POSTGRES_DB: budget_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget"]
      interval: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
